[package]
name = "cyfer-core"
version = "0.1.0"
edition = "2024"


[dependencies]
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rand = "0.8"
aes-gcm = { version = "0.10.3", features = ["aes"] }
argon2 = "0.5"
base64 = "0.22"
dirs = "5"
zeroize = "1"